//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegendGenerator.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LegendGenerator.App.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string btnAbbrechen {
            get {
                return ResourceManager.GetString("btnAbbrechen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        public static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legende erstellen.
        /// </summary>
        public static string btnCreateLegend {
            get {
                return ResourceManager.GetString("btnCreateLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style Dump - Tabelle.
        /// </summary>
        public static string btnDumpStyle {
            get {
                return ResourceManager.GetString("btnDumpStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwende Nummerierung aus der Datenbank.
        /// </summary>
        public static string btnLegendNumberDatabase {
            get {
                return ResourceManager.GetString("btnLegendNumberDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legenden - Template.
        /// </summary>
        public static string btnLegendTemplate {
            get {
                return ResourceManager.GetString("btnLegendTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Access-Tabellen.
        /// </summary>
        public static string btnLoadAccessTables {
            get {
                return ResourceManager.GetString("btnLoadAccessTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade SQL Server Tabellen.
        /// </summary>
        public static string btnLoadSqlServerTables {
            get {
                return ResourceManager.GetString("btnLoadSqlServerTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset PageLayout.
        /// </summary>
        public static string btnResetGraphicsContainer {
            get {
                return ResourceManager.GetString("btnResetGraphicsContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylefile hinzufügen.
        /// </summary>
        public static string btnStylefileAdd {
            get {
                return ResourceManager.GetString("btnStylefileAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilder nicht abspeichern.
        /// </summary>
        public static string btnSymbolNotSave {
            get {
                return ResourceManager.GetString("btnSymbolNotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilder abspeichern.
        /// </summary>
        public static string btnSymbolOk {
            get {
                return ResourceManager.GetString("btnSymbolOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Verwende Access.
        /// </summary>
        public static string chkAccess {
            get {
                return ResourceManager.GetString("chkAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   L__NUM mit 0-Werten zulassen.
        /// </summary>
        public static string chkAllowNullLegendNumber {
            get {
                return ResourceManager.GetString("chkAllowNullLegendNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   SQL Authentifizierung.
        /// </summary>
        public static string chkAuthentifizierung {
            get {
                return ResourceManager.GetString("chkAuthentifizierung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Farbwerte in der Legende zeichnen.
        /// </summary>
        public static string chkFarbwerte {
            get {
                return ResourceManager.GetString("chkFarbwerte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   verwende fortlaufende Nummerierung.
        /// </summary>
        public static string chkFortlaufendeNummer {
            get {
                return ResourceManager.GetString("chkFortlaufendeNummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   *.gif Export.
        /// </summary>
        public static string chkGifExport {
            get {
                return ResourceManager.GetString("chkGifExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Verwende SDE.
        /// </summary>
        public static string chkSde {
            get {
                return ResourceManager.GetString("chkSde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   nur sichtbaren Bereich berücksichtigen.
        /// </summary>
        public static string chkSpatialQuery {
            get {
                return ResourceManager.GetString("chkSpatialQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Deutsch.
        /// </summary>
        public static string chkSpracheDeutsch {
            get {
                return ResourceManager.GetString("chkSpracheDeutsch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Englisch.
        /// </summary>
        public static string chkSpracheEnglisch {
            get {
                return ResourceManager.GetString("chkSpracheEnglisch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulardaten speichern.
        /// </summary>
        public static string groupBox5 {
            get {
                return ResourceManager.GetString("groupBox5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessdatenbank:.
        /// </summary>
        public static string lblAccessDatabase {
            get {
                return ResourceManager.GetString("lblAccessDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUERY (z.B. L__SORT LIKE &apos;a*&apos; and HEADING1 LIKE &apos;Quartär*&apos;):.
        /// </summary>
        public static string lblAttributeQuery {
            get {
                return ResourceManager.GetString("lblAttributeQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufdruck - BLAU:.
        /// </summary>
        public static string lblAufdruckBlau {
            get {
                return ResourceManager.GetString("lblAufdruckBlau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufdruck - BRAUN:.
        /// </summary>
        public static string lblAufdruckBraun {
            get {
                return ResourceManager.GetString("lblAufdruckBraun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufdruck - CYAN:.
        /// </summary>
        public static string lblAufdruckCyan {
            get {
                return ResourceManager.GetString("lblAufdruckCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufdruck - GELB:.
        /// </summary>
        public static string lblAufdruckGelb {
            get {
                return ResourceManager.GetString("lblAufdruckGelb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufdruck - GRAU:.
        /// </summary>
        public static string lblAufdruckGrau {
            get {
                return ResourceManager.GetString("lblAufdruckGrau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufdruck - GRÜN:.
        /// </summary>
        public static string lblAufdruckGruen {
            get {
                return ResourceManager.GetString("lblAufdruckGruen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufdruck - MAGENTA:.
        /// </summary>
        public static string lblAufdruckMagenta {
            get {
                return ResourceManager.GetString("lblAufdruckMagenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufdruck - ORANGE:.
        /// </summary>
        public static string lblAufdruckOrange {
            get {
                return ResourceManager.GetString("lblAufdruckOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufdruck - ROT:.
        /// </summary>
        public static string lblAufdruckRot {
            get {
                return ResourceManager.GetString("lblAufdruckRot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenbank:.
        /// </summary>
        public static string lblDatabase {
            get {
                return ResourceManager.GetString("lblDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verknüpfungs ID:.
        /// </summary>
        public static string lblDatabaseId {
            get {
                return ResourceManager.GetString("lblDatabaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitere Einstellungen:.
        /// </summary>
        public static string lblEinstellungen {
            get {
                return ResourceManager.GetString("lblEinstellungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flächensymbolname:.
        /// </summary>
        public static string lblFlaeche {
            get {
                return ResourceManager.GetString("lblFlaeche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppierung:.
        /// </summary>
        public static string lblGruppierung {
            get {
                return ResourceManager.GetString("lblGruppierung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infozeile 4:.
        /// </summary>
        public static string lblInfozeile4 {
            get {
                return ResourceManager.GetString("lblInfozeile4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infozeile 5:.
        /// </summary>
        public static string lblInfozeile5 {
            get {
                return ResourceManager.GetString("lblInfozeile5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infozeile 6:.
        /// </summary>
        public static string lblInfozeile6 {
            get {
                return ResourceManager.GetString("lblInfozeile6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instanz:.
        /// </summary>
        public static string lblInstance {
            get {
                return ResourceManager.GetString("lblInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kästchen - Legendentext - Abstand:.
        /// </summary>
        public static string lblKaestchenLegendentextAbstand {
            get {
                return ResourceManager.GetString("lblKaestchenLegendentextAbstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klammerabstand:.
        /// </summary>
        public static string lblKlammerabstand {
            get {
                return ResourceManager.GetString("lblKlammerabstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klammerebene 1:.
        /// </summary>
        public static string lblKlammerebene1 {
            get {
                return ResourceManager.GetString("lblKlammerebene1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klammerebene 2:.
        /// </summary>
        public static string lblKlammerebene2 {
            get {
                return ResourceManager.GetString("lblKlammerebene2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klammerebene 3:.
        /// </summary>
        public static string lblKlammerebene3 {
            get {
                return ResourceManager.GetString("lblKlammerebene3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfigurationsdatei:.
        /// </summary>
        public static string lblKonfigurationsdatei {
            get {
                return ResourceManager.GetString("lblKonfigurationsdatei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendengrafik:.
        /// </summary>
        public static string lblLegendengrafik {
            get {
                return ResourceManager.GetString("lblLegendengrafik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lfde Legendennummer:.
        /// </summary>
        public static string lblLegendennummer {
            get {
                return ResourceManager.GetString("lblLegendennummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendentext:.
        /// </summary>
        public static string lblLegendentext {
            get {
                return ResourceManager.GetString("lblLegendentext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendentabelle:.
        /// </summary>
        public static string lblLegendTable {
            get {
                return ResourceManager.GetString("lblLegendTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendentabelle - Pfade und Feldnamen.
        /// </summary>
        public static string lblLegendtablePaths {
            get {
                return ResourceManager.GetString("lblLegendtablePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liniensymbolname:.
        /// </summary>
        public static string lblLinie {
            get {
                return ResourceManager.GetString("lblLinie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markersymbolname:.
        /// </summary>
        public static string lblMarker {
            get {
                return ResourceManager.GetString("lblMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nach Überschrift 1:.
        /// </summary>
        public static string lblNachUeberschrift1 {
            get {
                return ResourceManager.GetString("lblNachUeberschrift1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nach Überschrift 2:.
        /// </summary>
        public static string lblNachUeberschrift2 {
            get {
                return ResourceManager.GetString("lblNachUeberschrift2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notizen:.
        /// </summary>
        public static string lblNotizen {
            get {
                return ResourceManager.GetString("lblNotizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notizen Offset:.
        /// </summary>
        public static string lblNotizenOffset {
            get {
                return ResourceManager.GetString("lblNotizenOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort:.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortierung:.
        /// </summary>
        public static string lblSortierschluessel {
            get {
                return ResourceManager.GetString("lblSortierschluessel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID:.
        /// </summary>
        public static string lblSpatialQueryId {
            get {
                return ResourceManager.GetString("lblSpatialQueryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        public static string lblSqlServer {
            get {
                return ResourceManager.GetString("lblSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevorzugter Symbol Style:.
        /// </summary>
        public static string lblStyle {
            get {
                return ResourceManager.GetString("lblStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie bitte ein Stylefile:.
        /// </summary>
        public static string lblStylefileLabel1 {
            get {
                return ResourceManager.GetString("lblStylefileLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylefile:.
        /// </summary>
        public static string lblStylefileLabel2 {
            get {
                return ResourceManager.GetString("lblStylefileLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überschrift 1:.
        /// </summary>
        public static string lblUeberschrift1 {
            get {
                return ResourceManager.GetString("lblUeberschrift1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überschrift 2:.
        /// </summary>
        public static string lblUeberschrift2 {
            get {
                return ResourceManager.GetString("lblUeberschrift2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überschrift 3:.
        /// </summary>
        public static string lblUeberschrift3 {
            get {
                return ResourceManager.GetString("lblUeberschrift3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendentext:.
        /// </summary>
        public static string lblUmbruchLegendentext {
            get {
                return ResourceManager.GetString("lblUmbruchLegendentext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einträge/Spalte:.
        /// </summary>
        public static string lblUmbruchSpaltenLaenge {
            get {
                return ResourceManager.GetString("lblUmbruchSpaltenLaenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spalten Offset [cm]:.
        /// </summary>
        public static string lblUmbruchSpaltenOffset {
            get {
                return ResourceManager.GetString("lblUmbruchSpaltenOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überschrift 1:.
        /// </summary>
        public static string lblUmbruchUeberschrift1 {
            get {
                return ResourceManager.GetString("lblUmbruchUeberschrift1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überschrift 2:.
        /// </summary>
        public static string lblUmbruchUeberschrift2 {
            get {
                return ResourceManager.GetString("lblUmbruchUeberschrift2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überschrift 3:.
        /// </summary>
        public static string lblUmbruchUeberschrift3 {
            get {
                return ResourceManager.GetString("lblUmbruchUeberschrift3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer:.
        /// </summary>
        public static string lblUser {
            get {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string lblVersion {
            get {
                return ResourceManager.GetString("lblVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertikalbstand:.
        /// </summary>
        public static string lblVertikalabstand {
            get {
                return ResourceManager.GetString("lblVertikalabstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vor Überschrift 1:.
        /// </summary>
        public static string lblVorUeberschrift1 {
            get {
                return ResourceManager.GetString("lblVorUeberschrift1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Offset:.
        /// </summary>
        public static string lblXoffset {
            get {
                return ResourceManager.GetString("lblXoffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-Offset:.
        /// </summary>
        public static string lblYoffset {
            get {
                return ResourceManager.GetString("lblYoffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeichenelemente:.
        /// </summary>
        public static string lblZeichenelemente {
            get {
                return ResourceManager.GetString("lblZeichenelemente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laden.
        /// </summary>
        public static string LoadObjectButton {
            get {
                return ResourceManager.GetString("LoadObjectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string mnuAppAbout {
            get {
                return ResourceManager.GetString("mnuAppAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applikation schließen.
        /// </summary>
        public static string mnuAppClose {
            get {
                return ResourceManager.GetString("mnuAppClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LegendGenerator-Hilfe.
        /// </summary>
        public static string mnuAppHelp {
            get {
                return ResourceManager.GetString("mnuAppHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfigurationsfile öffnen.
        /// </summary>
        public static string mnuAppLoad {
            get {
                return ResourceManager.GetString("mnuAppLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei speichern.
        /// </summary>
        public static string mnuAppSave {
            get {
                return ResourceManager.GetString("mnuAppSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei speichern unter.
        /// </summary>
        public static string mnuAppSaveNew {
            get {
                return ResourceManager.GetString("mnuAppSaveNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenbankeinstellungen.
        /// </summary>
        public static string mnuDatenbankeinstellungen {
            get {
                return ResourceManager.GetString("mnuDatenbankeinstellungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string mnuEinstellungen {
            get {
                return ResourceManager.GetString("mnuEinstellungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei.
        /// </summary>
        public static string mnuFile {
            get {
                return ResourceManager.GetString("mnuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fortlaufende Nummerierung.
        /// </summary>
        public static string mnuFortlaufendeNummer {
            get {
                return ResourceManager.GetString("mnuFortlaufendeNummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol Export.
        /// </summary>
        public static string mnuGraphicExport {
            get {
                return ResourceManager.GetString("mnuGraphicExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe.
        /// </summary>
        public static string mnuHilfe {
            get {
                return ResourceManager.GetString("mnuHilfe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string mnuInfo {
            get {
                return ResourceManager.GetString("mnuInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylefile laden.
        /// </summary>
        public static string mnuLoadStylefile {
            get {
                return ResourceManager.GetString("mnuLoadStylefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Legend.
        /// </summary>
        public static string mnuResetPage {
            get {
                return ResourceManager.GetString("mnuResetPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeige XML-File.
        /// </summary>
        public static string mnuShowXml {
            get {
                return ResourceManager.GetString("mnuShowXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spracheinstellungen.
        /// </summary>
        public static string mnuSpracheinstellungen {
            get {
                return ResourceManager.GetString("mnuSpracheinstellungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindungseinstellungen.
        /// </summary>
        public static string mnuVerbindung {
            get {
                return ResourceManager.GetString("mnuVerbindung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string SaveObjectButton {
            get {
                return ResourceManager.GetString("SaveObjectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access -Datenbank.
        /// </summary>
        public static string tabItemAccess {
            get {
                return ResourceManager.GetString("tabItemAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schmuckfarben.
        /// </summary>
        public static string tabItemAufdrucksfarben {
            get {
                return ResourceManager.GetString("tabItemAufdrucksfarben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenbankspalten.
        /// </summary>
        public static string tabItemDatenbankspalten {
            get {
                return ResourceManager.GetString("tabItemDatenbankspalten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positionierung.
        /// </summary>
        public static string tabItemGrafPos {
            get {
                return ResourceManager.GetString("tabItemGrafPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitere Datenbankspalten.
        /// </summary>
        public static string tabItemOptionaleDatenbankspalten {
            get {
                return ResourceManager.GetString("tabItemOptionaleDatenbankspalten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDE - Datenbank.
        /// </summary>
        public static string tabItemSde {
            get {
                return ResourceManager.GetString("tabItemSde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        public static string tabItemSelektion {
            get {
                return ResourceManager.GetString("tabItemSelektion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbruch.
        /// </summary>
        public static string tabItemUmbruch {
            get {
                return ResourceManager.GetString("tabItemUmbruch", resourceCulture);
            }
        }
    }
}
